apiVersion: v1
kind: Namespace
metadata:
  name: talos-backup
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: talos-backup-secrets
  namespace: talos-backup
spec:
  roles:
    - os:etcd:backup
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: talos-backup
  namespace: talos-backup
spec:
  schedule: '0 */6 * * *'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          containers:
            - name: talos-backup
              image: ghcr.io/siderolabs/talos-backup:v0.1.0-beta.3
              workingDir: /tmp
              command:
                - /talos-backup
              env:
                - name: CLUSTER_NAME
                  value: spire
                - name: BUCKET
                  value: spire-etcd-backups
                - name: S3_PREFIX
                  value: spire
                - name: AWS_REGION
                  value: garage
                - name: USE_PATH_STYLE
                  value: 'true'
                - name: AGE_X25519_PUBLIC_KEY
                  value: age1hafr9j7hllceaqedmycevuefzcpp36a96tse8mqq9d2d3ts6f3pssyeffa
                - name: CUSTOM_S3_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: talos-backup-s3
                      key: endpoint
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: talos-backup-s3
                      key: access-key-id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: talos-backup-s3
                      key: secret-access-key
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
              volumeMounts:
                - mountPath: /tmp
                  name: tmp
                - mountPath: /.talos
                  name: talos
                - mountPath: /var/run/secrets/talos.dev
                  name: talos-secrets
          volumes:
            - name: tmp
              emptyDir: {}
            - name: talos
              emptyDir: {}
            - name: talos-secrets
              secret:
                secretName: talos-backup-secrets
